In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import zscore 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [31]:
df=pd.read_csv("travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [32]:
df.drop("CustomerID",axis=1,inplace=True)

In [33]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [34]:
df.isna().sum()

ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ProdTaken                 4888 non-null   int64
 1   Age                       4662 non-null   float64
 2   TypeofContact             4863 non-null   object
 3   CityTier                  4888 non-null   int64
 4   DurationOfPitch           4637 non-null   float64
 5   Occupation                4888 non-null   object
 6   Gender                    4888 non-null   object
 7   NumberOfPersonVisiting    4888 non-null   int64
 8   NumberOfFollowups         4843 non-null   float64
 9   ProductPitched            4888 non-null   object
 10  PreferredPropertyStar     4862 non-null   float64
 11  MaritalStatus             4888 non-null   object
 12  NumberOfTrips             4748 non-null   float64
 13  Passport                  4888 non-null   int64
 14  PitchSatisfactionScore    4888 non-null   int64
 15  OwnCar                    4888 non-null   int64
 16  NumberOfChildrenVisiting  4822 non-null   float64
 17  Designation               4888 non-null   object
 18  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(6), object(6)
memory usage: 725.7+ KB

In [36]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [37]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [38]:
df["Gender"].replace("Fe Male","Female",inplace=True)

In [39]:
df["MaritalStatus"].replace("Single","Unmarried",inplace=True)

In [40]:
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [41]:
df.isna().sum()

ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [45]:
df["Age"].fillna(df["Age"].median(),inplace=True)
df["TypeofContact"].fillna(df["TypeofContact"].mode()[0],inplace=True)
df["DurationOfPitch"].fillna(df["DurationOfPitch"].median(),inplace=True)
df["NumberOfFollowups"].fillna(df["NumberOfFollowups"].mode()[0],inplace=True)
df["PreferredPropertyStar"].fillna(df["PreferredPropertyStar"].mode()[0],inplace=True)
df["NumberOfTrips"].fillna(df["NumberOfTrips"].mode()[0],inplace=True)
df["NumberOfChildrenVisiting"].fillna(df["NumberOfChildrenVisiting"].mode()[0],inplace=True)
df["MonthlyIncome"].fillna(df["MonthlyIncome"].median(),inplace=True)

In [46]:
df["TotalVisiting"]=df["NumberOfChildrenVisiting"]+df["NumberOfPersonVisiting"]

In [47]:
df.drop(columns=["NumberOfChildrenVisiting","NumberOfPersonVisiting"],axis=1,inplace=True)

In [48]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [49]:
# get all the numerical feture
num_features=[feature for feature in df.columns if df[feature].dtype!="O"]
print("Num of Numerical Features:",len(num_features))

Num of Numerical Features: 12

In [50]:
cat_features=[feature for feature in df.columns if df[feature].dtype=="O"]
print("Num of categorical Features:",len(cat_features))

Num of categorical Features: 6

In [52]:
le=LabelEncoder()
cat_features=df.select_dtypes(include="object")
for i in cat_features:
    df[i]=le.fit_transform(df[i])

In [53]:
z=np.abs(zscore(df))
df1=df[(z<3).all(axis=1)]
df.shape

(4888, 18)

In [54]:
df1.shape

(4876, 18)

In [55]:
df=df1.copy()

In [57]:
X=df.drop(["ProdTaken"],axis=1)
y=df["ProdTaken"]

In [59]:
sc=StandardScaler()
X_sc=sc.fit_transform(X)

In [60]:
maxAccu=0
maxRS=0
for i in range(1,250):
    X_train,X_test,y_train,y_test=train_test_split(X_sc,y,test_size=0.3,random_state=i)
    dtc=DecisionTreeClassifier()
    dtc.fit(X_train,y_train)
    y_pred=dtc.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    if acc>maxAccu:
        maxAccu=acc
        maxRS=i
print("Best accuracy is",maxAccu,"on RandomState",maxRS)

Best accuracy is 0.9241285030758715 on RandomState 111

In [61]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,test_size=0.3,random_state=111)

In [62]:
X_train.shape

(3413, 17)

In [63]:
X_test.shape

(1463, 17)

In [64]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1196
           1       0.78      0.79      0.78       267

    accuracy                           0.92      1463
   macro avg       0.87      0.87      0.87      1463
weighted avg       0.92      0.92      0.92      1463

In [66]:
param_grid={
    "criterion":["gini","entropy"],
    "max_depth":[5,8,15,10],
    "min_samples_split":[2,8,15,20]
}

In [67]:
grid_search=GridSearchCV(dtc,param_grid,cv=5)
grid_search.fit(X_train,y_train)
print("Best Params:",grid_search.best_params_)

Best Params: {'criterion': 'entropy', 'max_depth': 15, 'min_samples_split': 2}

In [68]:
final_mod=DecisionTreeClassifier(criterion="entropy",max_depth=15, min_samples_split= 2)
final_mod.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=15)

In [69]:
y_pred=final_mod.predict(X_test)
print("Accuracy Score:\n",accuracy_score(y_test,y_pred))

Accuracy Score:
 0.9179767600820232